# Generated by Django 5.2.5 on 2025-09-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('move_type', models.CharField(choices=[('Normal', 'Special'), ('Normal', 'Special')], default='Normal', max_length=50)),
                ('damage', models.CharField(max_length=10)),
                ('guard_type', models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High')], default='Mid', max_length=20)),
                ('start_up', models.IntegerField()),
                ('active', models.IntegerField()),
                ('recovery', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move', to='main_app.character')),
            ],
        ),
    ]
