# Generated by Django 5.2.5 on 2025-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('sol', 'sol'), ('ky', 'ky')], default='sol', max_length=50),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special')], default='Normal', max_length=50),
        ),
    ]
