# Generated by Django 5.2.5 on 2025-09-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='character',
            table='characters',
        ),
        migrations.AlterModelTable(
            name='move',
            table='moves',
        ),
    ]
