# Generated by Django 5.2.5 on 2025-09-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_character_name_alter_move_move_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='move',
            name='character',
            field=models.ForeignKey(choices=[('sol', 'sol'), ('ky', 'ky')], default='sol', on_delete=django.db.models.deletion.CASCADE, related_name='move', to='main_app.character'),
        ),
    ]
