# Generated by Django 5.2.5 on 2025-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_character_name_alter_move_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('sol', 'sol'), ('ky', 'ky')], default='sol', max_length=50),
        ),
    ]
