# Generated by Django 5.2.5 on 2025-09-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='move',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='main_app.character'),
        ),
    ]
