# Generated by Django 5.2.5 on 2025-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_character_name_alter_move_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_store/'),
        ),
    ]
