# Generated by Django 5.2.5 on 2025-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_move_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_store/'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_store/'),
        ),
    ]
