# Generated by Django 5.2.5 on 2025-09-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_character_character_image_game_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_image',
            new_name='image',
        ),
    ]
