# Generated by Django 5.2.5 on 2025-09-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_character_image_character_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
