# Generated by Django 5.2.5 on 2025-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_move_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='onblock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='onhit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
