# Generated by Django 5.2.5 on 2025-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_move_onblock_move_onhit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special'), ('Super', 'Super')], default='Normal', max_length=50),
        ),
    ]
